### ISSUE TITLE
Test the theme with AMP plugin

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#150]
We should test if we get any errors when creating a theme with AMP plugin installed.

**Comment by gabriel-glo** [comment]
I tested the fresh install of WP Boilerplate with [official AMP plugin](https://amp-wp.org/) and results are varying.
First of all the plugin offers three modes of serving AMP pages.

### Reader mode 
It generates a simplified version of the page and injects the content in its own layout. Original page is still present and AMP version is accessible by adding `?amp` URL parameter to the URL. Could be useful for blog posts and pages that don't use complicated blocks. It could work for more complex blocks, but AMP removes standard `box-sizing` definition and any standard flex/grid layout breaks because of that. Maybe there is a way to inject that style rule back to AMP version

![image](https://user-images.githubusercontent.com/41635034/89912077-6f0e5400-dbf2-11ea-8eb5-b099ec460a55.png)
![image](https://user-images.githubusercontent.com/41635034/89912109-77668f00-dbf2-11ea-8820-14b754a80cb6.png)

### Transitional mode
Uses WP templates and blocks to generate AMP version of the page while keeping the layout of the page as close to the original as possible. Original page is still present and AMP version is accessible by adding `?amp` URL parameter to the URL. Due to the way AMP works, it finds issues with enqueued scripts, and in our case those are `application.js` and `applicationBlocks.js`. By default AMP plugin removes those scripts in the AMP version of the page, so none of the custom interactions will not work (opening/closing the mobile menu, accordions, modals, .etc). There is no elegant solution to this problem and only thing I see that will work is if the JS functionalities are rewritten for AMP version of the page [https://amp-wp.org/documentation/developing-wordpress-amp-sites/how-to-develop-with-the-amp-plugin/](https://amp-wp.org/documentation/developing-wordpress-amp-sites/how-to-develop-with-the-amp-plugin/)

Side by side view of the non-AMP and AMP version of the site. On both pages the menu toggle has been clicked.
![image](https://user-images.githubusercontent.com/41635034/89915947-46d52400-dbf7-11ea-893b-7fa5b2172734.png)

### Standard mode
AMP version of the page becomes the default version and only AMP templates are used to render the page. This is not something we would want to use.
