### ISSUE TITLE
`npx create-wp-theme --branch=master` fails

### ISSUE THREAD

**Issue by foodlydoodlydoo** [infinum/eightshift-boilerplate#156]
`create-wp-theme` tries to replace theme data in files expected for the `development` branch being cloned and fails to find them.  The whole theme creation thus fails.

What I'm trying to do is to incorporate changes to the master branch of wp-boilerplate between the time I created the theme the first time (~6 months ago) and your current HEAD.  The changes would be a diff between my local 6-months old 'init' commit and what I get now when I create the theme again providing the same theme data (having just all the inf_theme -> my_theme_name replacements).  Then apply that diff on my "init" commit (creating a new base commit) and then rebase (possibly semi-automaticly) all my theme changes, now based on my old "init" commit, on top of this new base commit.

----

Note that updating and merging your bug fixes to the boilerplate base code is really painful.  Some update mechanism (specifically for security bugs beyond solvable with `npm audit fix`) would be great to think of, but I understand it may too hard.

Also, if I wanted to rebase on top of the upcoming 'development' branch (where stuff is pretty much reorganized), is there some doc about what has been moved where so one could try to rebase?

Thanks.

**Comment by foodlydoodlydoo** [comment]
Regarding my attempt to grab the latests changes, eventually I simply looked at `git diff 787243247193ebce003d83713f3bf96df731232e HEAD -w`, and I found only following interesting changes:

- npm package updates (ran `npm update`, `npm audit fix` and selectively `npm install ...@latest or @^N` to get in sync) 
- composer updates (ran `composer update`)
- changes to webpack.config.js
- changes to theme/class-theme.php

anything else were minor and not critical or necessary. the first two steps are probably normal good hygiene (sorry for my npm ignorance ;))

-----

Leaving this issue open for the original `create-wp-theme` problem.

**Comment by dingo-d** [comment]
We're currently working on updating and releasing the new scripts which should have all these issues fixed. Also a new boilerplate version will be out pretty soon.

@IvanGrginovInf This sounds like a issue for you 😄

**Comment by IvanGrginovInf** [comment]
@foodlydoodlydoo The `--branch` argument is more there for testing rather than anything else but I definitely see how you might want to do this. The problem is the setup script and the fact that you can't version the setup script in the same way. Since there are currently major changes between development and master branches it would be just too much work in making the setup script work with both.

Anyway, like dingo-d said, we're currently in the process of releasing a new version and should fix everything in the next few days.

As for the "hard update mechanism", yes that's definitely true and would love for us to come up with some kind of way to make that easier but that's a bit harder problem to solve.

**Comment by foodlydoodlydoo** [comment]
Thank you.  Feel free to close/duplicate this issue at will.

Regarding the possible update to the new version to be able to sync fixes to at least a similar extent as I described in https://github.com/infinum/wp-boilerplate/issues/156#issuecomment-511123510 I think a good change-list doc would be super helpful.

Having a more automated way for major update rebase is a project on its own, yes :)
