### ISSUE TITLE
Enqueue style and Script on specific page templates

### ISSUE THREAD

**Issue by emisrw** [infinum/eightshift-boilerplate#168]
How can i enqueue style and script on specific page templates ? What steps should I do?

**Comment by IvanGrginovInf** [comment]
Hi @emisrw,

This question isn't really related to our boilerplate but here's how:
https://wordpress.stackexchange.com/questions/61244/wp-enqueue-style-on-specific-page-templates

Also, you don't really need to do that for JS since you can use [dynamic import](https://medium.com/front-end-weekly/webpack-and-dynamic-imports-doing-it-right-72549ff49234).

So instead of doing:

```js
import { object } from 'some-package';
```

You can do:

```js
if (/* some selector exist*/) {
  import('some-package').then(({ object }) => {
    // do something
  });
}
```

This way your package (script) will only be loaded if a specific condition is met (i.e. if you're on specific page).

Hope that helps.

**Comment by gabriel-glo** [comment]
Scripts and styles for theme are registered and enqueued in `class-theme.php`.
Scripts and styles for admin are registered and enqueued in `class-admin.php`.

For specific pages and templates you can use an appropriate conditional tag (https://developer.wordpress.org/themes/basics/conditional-tags/) and enqueuing specific assets inside that conditional.

Scripts and styles enqueued this way will not be included in build process.
If you want that you should use method explained above 🆙
