### ISSUE TITLE
Plugin installation leaves the main file name eightshift-boilerplate.php

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#200]
It seems that when you run `npx create-wp-project plugin` the rename script is not changing the main entrypoint file, or contents of the docblock.

In my plugin I have `eightshift-boilerplate.php` with

```php
<?php
/**
 * Plugin Name: Eightshift Boilerplate Title
 * Plugin URI:
 * Description: Eightshift Boilerplate Description
 * Author: Team Eightshift
 * Author URI: https://eightshift.com/
 * Version: 1.0.0
 * Text Domain: this-is-correctly-changed
 *
 * @package This_Is_Correctly_Changed
 *
 * @since 1.0.0
 */
```

**Comment by IvanGrginovInf** [comment]
This is because we haven't tweaked the setup script for plugins, it's looking for `Theme name: Something` to replace. I just need to tweak the rename function.

Also, it might make more sense to put issues like these (related to setup) in https://github.com/infinum/eightshift-frontend-libs (where setup script lives).

**Comment by dingo-d** [comment]
Wasn't aware of this, kinda hard to keep track of where everything is 😬 I'll open an issue upstream.
